import{S as d,i as m}from"./assets/vendor-BrddEoy-.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function t(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=t(r);fetch(r.href,o)}})();const p="46865368-ded5de9c0791206e82b93b274",l=new URLSearchParams({key:p,q:"",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:12}),g=s=>(l.set("q",s),fetch(`https://pixabay.com/api/?${l}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{if(e.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return e.hits.map(t=>({webformatURL:t.webformatURL,largeImageURL:t.largeImageURL,tags:t.tags,likes:t.likes,views:t.views,comments:t.comments,downloads:t.downloads}))}).catch(e=>{throw e})),y=({webformatURL:s,largeImageURL:e,tags:t,likes:i,views:r,comments:o,downloads:n})=>`<li class="gallery-item">
    <a class="gallery-link" href="${e}">
      <img class="gallery-img" src="${s}" alt="${t}" />
      <div class="gallery-img-info">
         <p class="info-item-title"><b>Likes</b>${i}</p>
          <p class="info-item-title"><b>Views</b>${r}</p>
          <p class="info-item-title"><b>Comments</b>${o}</p>
          <p class="info-item-title"><b>Downloads</b>${n}</p>
         
        </div>
    </a>
  </li>`,a=new d(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,animationSpeed:300,overlay:!0,overlayOpacity:.5});a.on("show.simplelightbox",function(){});a.on("closed.simplelightbox",function(){});const h=(s,e)=>{s.innerHTML=e.map(t=>y(t)).join(""),a.refresh()},b=document.querySelector(".search-form");document.querySelector(".loader");const c=document.querySelector(".gallery"),w=document.querySelector(".text-input"),f=document.querySelector(".loader-container"),L=(s,e,t)=>{m[s]({title:e,message:t,timeout:2500,progressBar:!1,position:"center"})},q=(s,e="")=>{L("error",e,s)};function v(){f.style.display="flex"}function u(){f.style.display="none"}b.addEventListener("submit",s=>{s.preventDefault();const e=w.value.trim();if(e.length!==0){if(!e){m.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}v(),g(e).then(t=>{h(c,t),u()}).catch(t=>{q(t.message),u(),c.innerHTML=""})}});
//# sourceMappingURL=index.js.map
